import { useRef } from "react";

export default function Portal() {
  const audioRef = useRef<HTMLAudioElement>(null);

  return (
    <div>
      <div
        className="page-container portal-page"
        onClick={() => audioRef.current?.play()}
      >
        <img src="/assets/image/logo.png" alt="Moomoo" />
        <h1>You did it!</h1>
        <p>
          Moomoo returned home through the waterfall portal, safe and sound.
        </p>
        <video autoPlay loop muted>
          <source src="/assets/video/portal.mp4" type="video/mp4" />
          <p>Your browser does not support the video tag.</p>
        </video>
        <audio ref={audioRef} autoPlay loop>
          <source
            src="/assets/audio/adventures-in-suburbia-looping.mp3"
            type="audio/mp3"
          />
          <p>Your browser does not support the audio tag.</p>
        </audio>
      </div>
      <div id="attribution">
        <p>
          <span>Tilesets by </span>
          <a href="https://zaebucca.itch.io/adventure-begins" target="_blank">
            Zaebucca
          </a>
          <br />
          <span>Sprites adapted from </span>
          <a href="https://joao9396.itch.io/pixel-cats-pack" target="_blank">
            Joao9396
          </a>
          <br />
          <span>Music by Eric Matyas, </span>
          <a href="https://soundimage.org" target="_blank">
            soundimage.com
          </a>
          <br />
          <span>Video generated by Sora, OpenAI</span>
          <br />
          <span>Story and puzzles by Vinesh Kannan</span>
        </p>
      </div>
    </div>
  );
}
